# When manually running the pipeline, you can select whether it
# succeeds or fails.
parameters:
- name: succeed
  displayName: Succeed or fail
  type: boolean
  default: false

trigger:
  batch: true
  branches:
    include:
    - main

pool:
  name: DemoPool
  vmImage: 'windows-2022'

variables:
  runEndToEnd: 'true'

# ---------------------------------

stages:
- stage: BuildStage
  displayName:  🏗 Build Stage
  dependsOn: []

  jobs:
  # this will create an error
  - job: HelloWorld
    displayName: Hello World
    steps:
    - script: |
        echo "Build reason: ${{variables['Build.Reason']}}"
        echo "Is it a pull request? ${{eq(variables['Build.Reason'], 'PullRequest')}}"

  # This job creates a work item, and only runs if the previous job failed
  - job: ErrorHandler
    dependsOn: HelloWorld
    condition: failed()
    steps: 
    - task: PowerShell@2
      displayName: Error Handler Feedback
      inputs:
        targetType: inline
        script: Write-Host 'Error on Hello world Job'
# ---------------------------------

- stage: IntegrationTestsStage
  displayName: 🧪 Run integration tests
  dependsOn: [ 'BuildStage' ]
  condition: succeeded('BuildStage')

  jobs:
  - job: FeedbackIntegrationTests
    displayName: Feedback Integration Tests
    steps:
    - task: PowerShell@2
      displayName: Feedback
      inputs:
        targetType: inline
        script: Write-Host 'Hello, World from Integration Tests stage!'

# ---------------------------------

- stage: EndToEndTestsStage
  displayName: 🤖 Run End to End tests
  dependsOn: [ 'BuildStage' ]
  condition: |
   and(
     eq(variables.runEndToEnd, 'true'), 
     succeeded('BuildStage')
     )
  
  jobs:
  - job: Feedback
    displayName: Feedback
    steps:
    - task: PowerShell@2
      displayName: Feedback
      inputs:
        targetType: inline
        script: Write-Host 'Hello, World from end 2 end stage!'