# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: DemoPool

variables:
  runEndToEnd: 'false'

# ---------------------------------

stages:
- stage: 🏗 Prebuild Stage
  displayName: Pre Build
  dependsOn: []

  jobs:
  - job: HelloWorld
    displayName: Hello World
    steps:
    - task: PowerShell@2
      displayName: Hello World
      inputs:
        targetType: inline
        script: Write-Host 'Hello, World!'