trigger:
- main

pool:
  name: DemoPool

variables:
  runEndToEnd: 'false'

# ---------------------------------

stages:
- stage: PreBuildStage
  displayName:  🏗 Prebuild Stage
  dependsOn: []

  jobs:
  - job: HelloWorld
    displayName: Hello World
    steps:
    - task: PowerShell@2
      displayName: Hello World
      inputs:
        targetType: inline
        script: Write-Host 'Hello, World from pre build stage!'

# ---------------------------------

- stage: EndToEndTestsStage
  displayName: 🤖 Run End to End tests
  dependsOn: [ 'BuildStage' ]
  condition: and(eq(variables.runEndToEnd, 'true'), succeeded('PreBuildStage'))
  
  jobs:
  - job: Feedback
    displayName: Feedback
    steps:
    - task: PowerShell@2
      displayName: Feedback
      inputs:
        targetType: inline
        script: Write-Host 'Hello, World from end 2 end stage!'